version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}         # <--- Variable
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # <--- Variable
      - POSTGRES_DB=${POSTGRES_DB}             # <--- Variable
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: cost_estimator_backend
    # Gunicorn for production performance
    command: gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}         # <--- Variable
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # <--- Variable
      - POSTGRES_SERVER=db                     # Internal docker name (keep as is)
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}             # <--- Variable
      - SECRET_KEY=${SECRET_KEY}               # <--- Variable
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440       # 24 Hours for prod
    depends_on:
      - db

  frontend:
    build: 
      context: ./cost-estimator-frontend
      dockerfile: Dockerfile.prod
    container_name: cost_estimator_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: