version: '3.8'

services:
  # 1. Database
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cost_estimator_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. PGAdmin
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  # 3. Backend (Python)
  backend:
    build: .
    container_name: cost_estimator_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=cost_estimator_db
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - db

  # 4. Frontend (Node/React)
  frontend:
    build: ./cost-estimator-frontend
    container_name: cost_estimator_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./cost-estimator-frontend:/app
      - /app/node_modules
    environment:
      # This URL is for the BROWSER (Your PC) to reach the backend
      - VITE_API_URL=http://localhost:8000
    stdin_open: true 
    tty: true
    depends_on:
      - backend

volumes:
  postgres_data: